services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: crawler_postgres
    environment:
      POSTGRES_DB: crawler_db
      POSTGRES_USER: crawler_user
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    restart: unless-stopped

  # Main Application
  crawler:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: crawler_app
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=crawler_db
      - DB_USER=crawler_user
      - DB_PASSWORD=your_secure_password
      - PORT=3004
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_SKIP_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    ports:
      - "3005:3004"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local 